# Generated by Django 5.1.3 on 2025-03-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='genres',
            field=models.JSONField(default=list),
        ),
    ]
