# Generated by Django 5.1.3 on 2025-03-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_novel_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='novel_images/'),
        ),
    ]
