# Generated by Django 5.1.3 on 2025-03-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0003_novel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='unpublished',
            field=models.BooleanField(default=False),
        ),
    ]
